/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "project-Blog_Project-PfADUFR5313hUPUzj4m0PUfClVX7R0xK",
  "version": "2020-11-20"
}

export default ebconfig;